DriverGenerator: tools.Utils Class Reference
tools.Utils Class Reference
Static Public Member Functions
static boolean isWindows ()
static boolean isMac ()
static boolean isUnix ()
static boolean isSolaris ()
static boolean isNumeric (String str)
static boolean is64bit ()
static int getStatusCode (String response)
static String nextSymbols (String current)
static String decapitalize (String s)
static String resetCharAt (String s, int pos)
static String incCharAt (String s, int pos)
static String capitalize (String s)
static String exec (String cmd)
static String escapeTags (String original)
static boolean randBoolWithPercent (int p)
static void copyFile (File in, File out) throws IOException
static int randIntBetween (int a, int b)
static< T > T randIn (List< T > l)
static< T > T randIn (T l[])
static int randInt (int max)
static< T > T randIn (Set< T > l)
static void browse (File log)
static boolean deleteDir (File path)
static boolean createDir (File dir)
static boolean cleanDir (File dir)
static String changeExtension (String originalName, String newExtension)
static< T > ArrayList< T > createArrayList (T...elements)
static< T > HashSet< T > createHashSet (T...elements)
static final String escapeHTML (String source)
static String removeExtension (String s)
static String makePath (String absolutePath)
static float meanOfCSVField (String filename, int i)
static float percentOfCSVField (String filename, int i, String value)
static String space (int length)
static String fileContentOf (String filename)
static String randString ()
static int minimum (int a, int b, int c)
static void saveToFile (String s, String filename)
Static Private Attributes
static Random rand = new Random()
Detailed Description
Definition at line 23 of file Utils.java.
Member Function Documentation
static void tools.Utils.browse (File log) static
Definition at line 184 of file Utils.java.
References tools.loggers.LogManager.logException().
static String tools.Utils.capitalize (String s) static
Definition at line 90 of file Utils.java.
static String tools.Utils.changeExtension (String originalName, String newExtension) static
Definition at line 234 of file Utils.java.
Referenced by tools.GraphViz.dotToFile().
static boolean tools.Utils.cleanDir (File dir) static
Definition at line 230 of file Utils.java.
References tools.Utils.createDir(), and tools.Utils.deleteDir().
static void tools.Utils.copyFile (File in, File out) throws IOException static
Definition at line 142 of file Utils.java.
static <T> ArrayList<T> tools.Utils.createArrayList (T... elements) static
Definition at line 245 of file Utils.java.
Referenced by crawler.WebInput.extractInputsFromForm().
static boolean tools.Utils.createDir (File dir) static
Definition at line 223 of file Utils.java.
Referenced by tools.Utils.cleanDir().
static <T> HashSet<T> tools.Utils.createHashSet (T... elements) static
Definition at line 254 of file Utils.java.
static String tools.Utils.decapitalize (String s) static
Definition at line 73 of file Utils.java.
static boolean tools.Utils.deleteDir (File path) static
Definition at line 207 of file Utils.java.
Referenced by tools.Utils.cleanDir().
static final String tools.Utils.escapeHTML (String source) static
Definition at line 262 of file Utils.java.
static String tools.Utils.escapeTags (String original) static
Definition at line 109 of file Utils.java.
static String tools.Utils.exec (String cmd) static
Definition at line 96 of file Utils.java.
Referenced by tools.GraphViz.check().
static String tools.Utils.fileContentOf (String filename) static
Definition at line 342 of file Utils.java.
static int tools.Utils.getStatusCode (String response) static
Definition at line 54 of file Utils.java.
static String tools.Utils.incCharAt (String s, int pos) static
Definition at line 83 of file Utils.java.
Referenced by tools.Utils.nextSymbols().
static boolean tools.Utils.is64bit () static
Definition at line 50 of file Utils.java.
Referenced by tools.GraphViz.check().
static boolean tools.Utils.isMac () static
Definition at line 32 of file Utils.java.
static boolean tools.Utils.isNumeric (String str) static
Definition at line 46 of file Utils.java.
Referenced by crawler.DriverGenerator.addInput().
static boolean tools.Utils.isSolaris () static
Definition at line 42 of file Utils.java.
static boolean tools.Utils.isUnix () static
Definition at line 36 of file Utils.java.
static boolean tools.Utils.isWindows () static
Definition at line 28 of file Utils.java.
Referenced by tools.GraphViz.check().
static String tools.Utils.makePath (String absolutePath) static
Definition at line 281 of file Utils.java.
static float tools.Utils.meanOfCSVField (String filename, int i) static
Definition at line 286 of file Utils.java.
static int tools.Utils.minimum (int a, int b, int c) static
Definition at line 361 of file Utils.java.
static String tools.Utils.nextSymbols (String current) static
Definition at line 60 of file Utils.java.
References tools.Utils.incCharAt(), and tools.Utils.resetCharAt().
static float tools.Utils.percentOfCSVField (String filename, int i, String value) static
Definition at line 311 of file Utils.java.
static boolean tools.Utils.randBoolWithPercent (int p) static
Definition at line 138 of file Utils.java.
static <T> T tools.Utils.randIn (List< T > l) static
Definition at line 164 of file Utils.java.
Referenced by crawler.DriverGenerator.getRandomValuesForInput(), crawler.DriverGenerator.getValuesForInput(), and crawler.DriverGenerator.submitRandom().
static <T> T tools.Utils.randIn (T l[]) static
Definition at line 169 of file Utils.java.
static <T> T tools.Utils.randIn (Set< T > l) static
Definition at line 179 of file Utils.java.
static int tools.Utils.randInt (int max) static
Definition at line 174 of file Utils.java.
Referenced by tools.Utils.randString().
static int tools.Utils.randIntBetween (int a, int b) static
Definition at line 154 of file Utils.java.
static String tools.Utils.randString () static
Definition at line 357 of file Utils.java.
References tools.Utils.randInt().
Referenced by crawler.DriverGenerator.addInput(), crawler.DriverGenerator.getRandomValuesForInput(), and crawler.DriverGenerator.getValuesForInput().
static String tools.Utils.removeExtension (String s) static
Definition at line 266 of file Utils.java.
static String tools.Utils.resetCharAt (String s, int pos) static
Definition at line 77 of file Utils.java.
Referenced by tools.Utils.nextSymbols().
static void tools.Utils.saveToFile (String s, String filename) static
Definition at line 365 of file Utils.java.
static String tools.Utils.space (int length) static
Definition at line 336 of file Utils.java.
Member Data Documentation
Random tools.Utils.rand = new Random() static private
Definition at line 24 of file Utils.java.
The documentation for this class was generated from the following file:
src/tools/Utils.java