DriverGenerator: main.drivergen.Main Class Reference
main.drivergen.Main Class Reference
Static Public Member Functions
static void hello ()
static void check (String[] args)
static void launch ()
static void main (String[] args) throws Exception
static void usage ()
Static Public Attributes
static Options Options
Detailed Description
Definition at line 11 of file Main.java.
Member Function Documentation
static void main.drivergen.Main.check (String[] args) static
Definition at line 22 of file Main.java.
References main.drivergen.Options.CSS, main.drivergen.Options.INPUT, main.drivergen.Options.JS, main.drivergen.Options.TIMEOUT, and main.drivergen.Main.usage().
Referenced by main.drivergen.Main.main().
static void main.drivergen.Main.hello () static
Definition at line 15 of file Main.java.
Referenced by main.drivergen.Main.main().
static void main.drivergen.Main.launch () static
Definition at line 39 of file Main.java.
References crawler.DriverGenerator.exportToDot(), crawler.DriverGenerator.exportToXML(), main.drivergen.Options.INPUT, and crawler.DriverGenerator.start().
Referenced by main.drivergen.Main.main().
static void main.drivergen.Main.main (String[] args) throws Exception static
Definition at line 58 of file Main.java.
References main.drivergen.Main.check(), main.drivergen.Main.hello(), and main.drivergen.Main.launch().
static void main.drivergen.Main.usage () static
Definition at line 69 of file Main.java.
Referenced by main.drivergen.Main.check().
Member Data Documentation
Options main.drivergen.Main.Options static
Definition at line 13 of file Main.java.
The documentation for this class was generated from the following file:
src/main/drivergen/Main.java