DriverGenerator: crawler.DriverGenerator Class Reference
crawler.DriverGenerator Class Reference
Public Member Functions
DriverGenerator (String configFileName) throws JsonParseException, JsonMappingException, IOException
String getName ()
void addUrl (String url)
void start ()
void exportToDot ()
void exportToXML ()
Protected Attributes
List< String > urlsToCrawl = null
List< WebInput > inputs = null
Map< String, ArrayList< String > > formValues = null
List< WebInput > sequence = null
WebClient client = null
HashSet< String > comments = null
ArrayList< WebOutput > outputs = null
ArrayList< WebTransition > transitions = null
List< Integer > currentNode = null
List< String > colors = null
int requests = 0
Static Protected Attributes
static Configuration config = null
Private Member Functions
void sendSequences ()
void reset ()
List< String > filterUrl (Elements links)
boolean addInput (WebInput in)
HTTPData getValuesForInput (WebInput in)
String submit (WebInput in) throws MalformedURLException
void mergeInputs ()
void initColor ()
int crawl (Document d, WebInput from, String content)
void addProvidedParameter (WebInput in)
Collection< Element > findFormsIn (String content, String baseUri)
void exportToDotCreateNodes (Writer w) throws IOException
String prettyprint (WebInput by)
int updateOutput (Document d, WebInput from)
HTTPData getRandomValuesForInput (WebInput in)
String submitRandom (WebInput in) throws MalformedURLException
void findParameters (List< WebInput > sequence, WebOutput out)
Set< String > findDifferences (WebOutput first, WebOutput second)
void findDifferences (Element first, Element second, Set< String > diff, List< String > pos)
int crawlInput (WebInput in)
Detailed Description
Definition at line 65 of file DriverGenerator.java.
Constructor & Destructor Documentation
crawler.DriverGenerator.DriverGenerator (String configFileName) throws JsonParseException, JsonMappingException, IOException
Definition at line 81 of file DriverGenerator.java.
References crawler.DriverGenerator.addUrl(), crawler.Configuration.check(), main.drivergen.Options.CSS, crawler.Configuration.getBasicAuthPass(), crawler.Configuration.getBasicAuthUser(), crawler.Configuration.getCookies(), crawler.Configuration.getData(), crawler.Configuration.getHost(), crawler.Configuration.getPort(), crawler.Configuration.getURLs(), main.drivergen.Options.JS, and main.drivergen.Options.TIMEOUT.
Member Function Documentation
boolean crawler.DriverGenerator.addInput (WebInput in) private
Definition at line 178 of file DriverGenerator.java.
References crawler.Configuration.getActionByParameter(), crawler.WebInput.getAddress(), crawler.WebInput.getParams(), tools.Utils.isNumeric(), crawler.Configuration.keepSmallSet(), and tools.Utils.randString().
Referenced by crawler.DriverGenerator.crawl().
void crawler.DriverGenerator.addProvidedParameter (WebInput in) private
Definition at line 480 of file DriverGenerator.java.
References crawler.Configuration.getData(), and crawler.WebInput.getParams().
Referenced by crawler.DriverGenerator.crawl().
void crawler.DriverGenerator.addUrl (String url)
Definition at line 343 of file DriverGenerator.java.
Referenced by crawler.DriverGenerator.DriverGenerator().
int crawler.DriverGenerator.crawl (Document d, WebInput from, String content) private
Definition at line 431 of file DriverGenerator.java.
References crawler.DriverGenerator.addInput(), crawler.DriverGenerator.addProvidedParameter(), crawler.DriverGenerator.crawlInput(), crawler.WebInput.extractInputsFromForm(), crawler.DriverGenerator.filterUrl(), crawler.DriverGenerator.findFormsIn(), crawler.Configuration.getLimitSelector(), crawler.DriverGenerator.sendSequences(), and crawler.DriverGenerator.updateOutput().
Referenced by crawler.DriverGenerator.crawlInput().
int crawler.DriverGenerator.crawlInput (WebInput in) private
Definition at line 675 of file DriverGenerator.java.
References crawler.DriverGenerator.crawl(), crawler.WebInput.Type.FORM, crawler.WebInput.getAddress(), crawler.WebInput.getParams(), crawler.WebInput.getType(), tools.loggers.LogManager.logException(), and crawler.DriverGenerator.submit().
Referenced by crawler.DriverGenerator.crawl(), and crawler.DriverGenerator.start().
void crawler.DriverGenerator.exportToDot ()
Definition at line 515 of file DriverGenerator.java.
References tools.GraphViz.dotToFile(), crawler.DriverGenerator.exportToDotCreateNodes(), crawler.Configuration.getName(), crawler.DriverGenerator.initColor(), tools.loggers.LogManager.logException(), and crawler.DriverGenerator.prettyprint().
Referenced by main.drivergen.Main.launch().
void crawler.DriverGenerator.exportToDotCreateNodes (Writer w) throws IOException private
Definition at line 509 of file DriverGenerator.java.
Referenced by crawler.DriverGenerator.exportToDot().
void crawler.DriverGenerator.exportToXML ()
Definition at line 696 of file DriverGenerator.java.
References crawler.Configuration.getBasicAuthPass(), crawler.Configuration.getBasicAuthUser(), crawler.Configuration.getCookies(), crawler.Configuration.getHost(), crawler.Configuration.getLimitSelector(), crawler.Configuration.getName(), crawler.Configuration.getPort(), tools.loggers.LogManager.logException(), main.drivergen.Options.NAME, and main.drivergen.Options.VERSION.
Referenced by main.drivergen.Main.launch().
List<String> crawler.DriverGenerator.filterUrl (Elements links) private
Definition at line 161 of file DriverGenerator.java.
References crawler.Configuration.getNoFollow().
Referenced by crawler.DriverGenerator.crawl().
Set<String> crawler.DriverGenerator.findDifferences (WebOutput first, WebOutput second) private
Definition at line 641 of file DriverGenerator.java.
References crawler.WebOutput.getDoc().
Referenced by crawler.DriverGenerator.findDifferences(), and crawler.DriverGenerator.findParameters().
void crawler.DriverGenerator.findDifferences (Element first, Element second, Set< String > diff, List< String > pos) private
Definition at line 656 of file DriverGenerator.java.
References crawler.DriverGenerator.findDifferences().
Collection<Element> crawler.DriverGenerator.findFormsIn (String content, String baseUri) private
Definition at line 490 of file DriverGenerator.java.
Referenced by crawler.DriverGenerator.crawl().
void crawler.DriverGenerator.findParameters (List< WebInput > sequence, WebOutput out) private
Definition at line 621 of file DriverGenerator.java.
References crawler.DriverGenerator.findDifferences(), crawler.Configuration.getLimitSelector(), crawler.WebOutput.getParams(), crawler.WebOutput.isEquivalentTo(), crawler.DriverGenerator.sendSequences(), and crawler.DriverGenerator.submitRandom().
Referenced by crawler.DriverGenerator.updateOutput().
String crawler.DriverGenerator.getName ()
Definition at line 134 of file DriverGenerator.java.
References crawler.Configuration.getName().
HTTPData crawler.DriverGenerator.getRandomValuesForInput (WebInput in) private
Definition at line 565 of file DriverGenerator.java.
References tools.HTTPData.add(), crawler.WebInput.Type.FORM, crawler.WebInput.getParams(), crawler.WebInput.getType(), tools.Utils.randIn(), and tools.Utils.randString().
Referenced by crawler.DriverGenerator.submitRandom().
HTTPData crawler.DriverGenerator.getValuesForInput (WebInput in) private
Definition at line 266 of file DriverGenerator.java.
References tools.HTTPData.add(), crawler.WebInput.Type.FORM, crawler.WebInput.getParams(), crawler.WebInput.getType(), tools.Utils.randIn(), and tools.Utils.randString().
Referenced by crawler.DriverGenerator.submit().
void crawler.DriverGenerator.initColor () private
Definition at line 418 of file DriverGenerator.java.
Referenced by crawler.DriverGenerator.exportToDot().
void crawler.DriverGenerator.mergeInputs () private
Definition at line 392 of file DriverGenerator.java.
References crawler.WebInput.getParams().
Referenced by crawler.DriverGenerator.start().
String crawler.DriverGenerator.prettyprint (WebInput by) private
Definition at line 541 of file DriverGenerator.java.
References crawler.Configuration.getActionByParameter(), crawler.WebInput.getAddress(), and crawler.WebInput.getParams().
Referenced by crawler.DriverGenerator.exportToDot().
void crawler.DriverGenerator.reset () private
Definition at line 149 of file DriverGenerator.java.
References crawler.Configuration.getReset(), tools.loggers.LogManager.logException(), and tools.loggers.LogManager.logFatalError().
Referenced by crawler.DriverGenerator.sendSequences(), and crawler.DriverGenerator.start().
void crawler.DriverGenerator.sendSequences () private
Definition at line 138 of file DriverGenerator.java.
References tools.loggers.LogManager.logException(), crawler.DriverGenerator.reset(), and crawler.DriverGenerator.submit().
Referenced by crawler.DriverGenerator.crawl(), and crawler.DriverGenerator.findParameters().
void crawler.DriverGenerator.start ()
Definition at line 348 of file DriverGenerator.java.
References crawler.DriverGenerator.crawlInput(), crawler.Configuration.getMerge(), crawler.DriverGenerator.mergeInputs(), and crawler.DriverGenerator.reset().
Referenced by main.drivergen.Main.launch().
String crawler.DriverGenerator.submit (WebInput in) throws MalformedURLException private
Definition at line 296 of file DriverGenerator.java.
References crawler.WebInput.Type.FORM, tools.HTTPData.getNameValueData(), crawler.DriverGenerator.getValuesForInput(), crawler.WebInput.Type.LINK, and tools.loggers.LogManager.logFatalError().
Referenced by crawler.DriverGenerator.crawlInput(), and crawler.DriverGenerator.sendSequences().
String crawler.DriverGenerator.submitRandom (WebInput in) throws MalformedURLException private
Definition at line 587 of file DriverGenerator.java.
References crawler.WebInput.Type.FORM, tools.HTTPData.getNameValueData(), crawler.DriverGenerator.getRandomValuesForInput(), crawler.WebInput.Type.LINK, and tools.Utils.randIn().
Referenced by crawler.DriverGenerator.findParameters().
int crawler.DriverGenerator.updateOutput (Document d, WebInput from) private
Definition at line 548 of file DriverGenerator.java.
References crawler.DriverGenerator.findParameters(), crawler.Configuration.getLimitSelector(), and crawler.WebOutput.isEquivalentTo().
Referenced by crawler.DriverGenerator.crawl().
Member Data Documentation
WebClient crawler.DriverGenerator.client = null protected
Definition at line 70 of file DriverGenerator.java.
List<String> crawler.DriverGenerator.colors = null protected
Definition at line 75 of file DriverGenerator.java.
HashSet<String> crawler.DriverGenerator.comments = null protected
Definition at line 71 of file DriverGenerator.java.
Configuration crawler.DriverGenerator.config = null static protected
Definition at line 78 of file DriverGenerator.java.
Referenced by crawler.WebOutput.WebOutput().
List<Integer> crawler.DriverGenerator.currentNode = null protected
Definition at line 74 of file DriverGenerator.java.
Map<String, ArrayList<String> > crawler.DriverGenerator.formValues = null protected
Definition at line 68 of file DriverGenerator.java.
List<WebInput> crawler.DriverGenerator.inputs = null protected
Definition at line 67 of file DriverGenerator.java.
ArrayList<WebOutput> crawler.DriverGenerator.outputs = null protected
Definition at line 72 of file DriverGenerator.java.
int crawler.DriverGenerator.requests = 0 protected
Definition at line 76 of file DriverGenerator.java.
List<WebInput> crawler.DriverGenerator.sequence = null protected
Definition at line 69 of file DriverGenerator.java.
ArrayList<WebTransition> crawler.DriverGenerator.transitions = null protected
Definition at line 73 of file DriverGenerator.java.
List<String> crawler.DriverGenerator.urlsToCrawl = null protected
Definition at line 66 of file DriverGenerator.java.
The documentation for this class was generated from the following file:
src/crawler/DriverGenerator.java