DriverGenerator: crawler.page.GenericTreeNode< T > Class Template Reference
crawler.page.GenericTreeNode< T > Class Template Reference
Public Member Functions
GenericTreeNode ()
GenericTreeNode (T data)
GenericTreeNode< T > getParent ()
List< GenericTreeNode< T > > getChildren ()
int getNumberOfChildren ()
boolean hasChildren ()
void setChildren (List< GenericTreeNode< T >> children)
void addChild (GenericTreeNode< T > child)
void addChildAt (int index, GenericTreeNode< T > child) throws IndexOutOfBoundsException
void removeChildren ()
void removeChildAt (int index) throws IndexOutOfBoundsException
GenericTreeNode< T > getChildAt (int index) throws IndexOutOfBoundsException
T getData ()
void setData (T data)
String toString ()
boolean equals (GenericTreeNode< T > node)
int hashCode ()
String toStringFull ()
String toString (int i)
Public Attributes
T data
List< GenericTreeNode< T > > children
GenericTreeNode< T > parent
Private Member Functions
String space (int depth)
Detailed Description
Definition at line 6 of file GenericTreeNode.java.
Constructor & Destructor Documentation
crawler.page.GenericTreeNode< T >.GenericTreeNode ()
Definition at line 12 of file GenericTreeNode.java.
crawler.page.GenericTreeNode< T >.GenericTreeNode (T data)
Definition at line 18 of file GenericTreeNode.java.
Member Function Documentation
void crawler.page.GenericTreeNode< T >.addChild (GenericTreeNode< T > child)
Definition at line 44 of file GenericTreeNode.java.
Referenced by crawler.page.PageTreeNode.extractPageTree().
void crawler.page.GenericTreeNode< T >.addChildAt (int index, GenericTreeNode< T > child) throws IndexOutOfBoundsException
Definition at line 49 of file GenericTreeNode.java.
boolean crawler.page.GenericTreeNode< T >.equals (GenericTreeNode< T > node)
Definition at line 78 of file GenericTreeNode.java.
GenericTreeNode<T> crawler.page.GenericTreeNode< T >.getChildAt (int index) throws IndexOutOfBoundsException
Definition at line 62 of file GenericTreeNode.java.
Referenced by crawler.page.PageTreeNode.equals().
List<GenericTreeNode<T> > crawler.page.GenericTreeNode< T >.getChildren ()
Definition at line 27 of file GenericTreeNode.java.
Referenced by crawler.page.GenericTreeNode< String >.getNumberOfChildren().
T crawler.page.GenericTreeNode< T >.getData ()
Definition at line 66 of file GenericTreeNode.java.
Referenced by crawler.page.GenericTreeNode< String >.equals(), crawler.page.GenericTreeNode< String >.hashCode(), and crawler.page.GenericTreeNode< String >.toString().
int crawler.page.GenericTreeNode< T >.getNumberOfChildren ()
Definition at line 31 of file GenericTreeNode.java.
Referenced by crawler.page.PageTreeNode.equals(), and crawler.page.GenericTreeNode< String >.hasChildren().
GenericTreeNode<T> crawler.page.GenericTreeNode< T >.getParent ()
Definition at line 23 of file GenericTreeNode.java.
boolean crawler.page.GenericTreeNode< T >.hasChildren ()
Definition at line 35 of file GenericTreeNode.java.
int crawler.page.GenericTreeNode< T >.hashCode ()
Definition at line 82 of file GenericTreeNode.java.
void crawler.page.GenericTreeNode< T >.removeChildAt (int index) throws IndexOutOfBoundsException
Definition at line 58 of file GenericTreeNode.java.
void crawler.page.GenericTreeNode< T >.removeChildren ()
Definition at line 54 of file GenericTreeNode.java.
void crawler.page.GenericTreeNode< T >.setChildren (List< GenericTreeNode< T >> children)
Definition at line 39 of file GenericTreeNode.java.
void crawler.page.GenericTreeNode< T >.setData (T data)
Definition at line 70 of file GenericTreeNode.java.
Referenced by crawler.page.GenericTreeNode< String >.GenericTreeNode().
String crawler.page.GenericTreeNode< T >.space (int depth) private
Definition at line 86 of file GenericTreeNode.java.
Referenced by crawler.page.GenericTreeNode< String >.toString().
String crawler.page.GenericTreeNode< T >.toString ()
Definition at line 74 of file GenericTreeNode.java.
Referenced by crawler.page.GenericTreeNode< String >.toStringFull().
String crawler.page.GenericTreeNode< T >.toString (int i)
Definition at line 96 of file GenericTreeNode.java.
String crawler.page.GenericTreeNode< T >.toStringFull ()
Definition at line 92 of file GenericTreeNode.java.
Member Data Documentation
List<GenericTreeNode<T> > crawler.page.GenericTreeNode< T >.children
Definition at line 9 of file GenericTreeNode.java.
Referenced by crawler.page.GenericTreeNode< String >.getChildren(), and crawler.page.GenericTreeNode< String >.setChildren().
T crawler.page.GenericTreeNode< T >.data
Definition at line 8 of file GenericTreeNode.java.
Referenced by crawler.page.PageTreeNode.equals(), crawler.page.GenericTreeNode< String >.getData(), and crawler.page.GenericTreeNode< String >.setData().
GenericTreeNode<T> crawler.page.GenericTreeNode< T >.parent
Definition at line 10 of file GenericTreeNode.java.
Referenced by crawler.page.GenericTreeNode< String >.addChild(), and crawler.page.GenericTreeNode< String >.getParent().
The documentation for this class was generated from the following file:
src/crawler/page/GenericTreeNode.java