DriverGenerator: tools.Base64 Class Reference
tools.Base64 Class Reference
Classes
class InputStream
class OutputStream
Static Public Member Functions
static void encode (java.nio.ByteBuffer raw, java.nio.ByteBuffer encoded)
static void encode (java.nio.ByteBuffer raw, java.nio.CharBuffer encoded)
static String encodeObject (java.io.Serializable serializableObject) throws java.io.IOException
static String encodeObject (java.io.Serializable serializableObject, int options) throws java.io.IOException
static String encodeBytes (byte[] source)
static String encodeBytes (byte[] source, int options) throws java.io.IOException
static String encodeBytes (byte[] source, int off, int len)
static String encodeBytes (byte[] source, int off, int len, int options) throws java.io.IOException
static byte[] encodeBytesToBytes (byte[] source)
static byte[] encodeBytesToBytes (byte[] source, int off, int len, int options) throws java.io.IOException
static byte[] decode (byte[] source) throws java.io.IOException
static byte[] decode (byte[] source, int off, int len, int options) throws java.io.IOException
static byte[] decode (String s) throws java.io.IOException
static byte[] decode (String s, int options) throws java.io.IOException
static Object decodeToObject (String encodedObject) throws java.io.IOException, java.lang.ClassNotFoundException
static Object decodeToObject (String encodedObject, int options, final ClassLoader loader) throws java.io.IOException, java.lang.ClassNotFoundException
static void encodeToFile (byte[] dataToEncode, String filename) throws java.io.IOException
static void decodeToFile (String dataToDecode, String filename) throws java.io.IOException
static byte[] decodeFromFile (String filename) throws java.io.IOException
static String encodeFromFile (String filename) throws java.io.IOException
static void encodeFileToFile (String infile, String outfile) throws java.io.IOException
static void decodeFileToFile (String infile, String outfile) throws java.io.IOException
Static Public Attributes
static final int NO_OPTIONS = 0
static final int ENCODE = 1
static final int DECODE = 0
static final int GZIP = 2
static final int DONT_GUNZIP = 4
static final int DO_BREAK_LINES = 8
static final int URL_SAFE = 16
static final int ORDERED = 32
Private Member Functions
Base64 ()
Static Private Member Functions
static final byte[] getAlphabet (int options)
static final byte[] getDecodabet (int options)
static byte[] encode3to4 (byte[] b4, byte[] threeBytes, int numSigBytes, int options)
static byte[] encode3to4 (byte[] source, int srcOffset, int numSigBytes, byte[] destination, int destOffset, int options)
static int decode4to3 (byte[] source, int srcOffset, byte[] destination, int destOffset, int options)
Static Private Attributes
static final int MAX_LINE_LENGTH = 76
static final byte EQUALS_SIGN = (byte)'='
static final byte NEW_LINE = (byte)'\n'
static final String PREFERRED_ENCODING = "US-ASCII"
static final byte WHITE_SPACE_ENC = -5
static final byte EQUALS_SIGN_ENC = -1
static final byte[] _STANDARD_ALPHABET
static final byte[] _STANDARD_DECODABET
static final byte[] _URL_SAFE_ALPHABET
static final byte[] _URL_SAFE_DECODABET
static final byte[] _ORDERED_ALPHABET
static final byte[] _ORDERED_DECODABET
Detailed Description
Definition at line 3 of file Base64.java.
Constructor & Destructor Documentation
tools.Base64.Base64 () private
Defeats instantiation.
Definition at line 296 of file Base64.java.
Member Function Documentation
static byte [] tools.Base64.decode (byte[] source) throws java.io.IOException static
Low-level access to decoding ASCII characters in the form of a byte array. Ignores GUNZIP option, if it's set. This is not generally a recommended method, although it is used internally as part of the decoding process. Special case: if len = 0, an empty array is returned. Still, if you need more speed and reduced memory footprint (and aren't gzipping), consider this method.
Parameters
source The Base64 encoded data
Returns
decoded data
Since
2.3.1
Definition at line 971 of file Base64.java.
References tools.Base64.NO_OPTIONS.
Referenced by tools.Base64.decode(), and tools.Base64.decodeToObject().
static byte [] tools.Base64.decode (byte[] source, int off, int len, int options) throws java.io.IOException static
Low-level access to decoding ASCII characters in the form of a byte array. Ignores GUNZIP option, if it's set. This is not generally a recommended method, although it is used internally as part of the decoding process. Special case: if len = 0, an empty array is returned. Still, if you need more speed and reduced memory footprint (and aren't gzipping), consider this method.
Parameters
source The Base64 encoded data
off The offset of where to begin decoding
len The length of characters to decode
options Can specify options such as alphabet type to use
Returns
decoded data
Exceptions
java.io.IOException If bogus characters exist in source data
Since
1.3
Definition at line 1001 of file Base64.java.
References tools.Base64.decode4to3(), and tools.Base64.getDecodabet().
static byte [] tools.Base64.decode (String s) throws java.io.IOException static
Decodes data from Base64 notation, automatically detecting gzip-compressed data and decompressing it.
Parameters
s the string to decode
Returns
the decoded data
Exceptions
java.io.IOException If there is a problem
Since
1.4
Definition at line 1076 of file Base64.java.
References tools.Base64.decode().
static byte [] tools.Base64.decode (String s, int options) throws java.io.IOException static
Decodes data from Base64 notation, automatically detecting gzip-compressed data and decompressing it.
Parameters
s the string to decode
options encode options such as URL_SAFE
Returns
the decoded data
Exceptions
java.io.IOException if there is an error
NullPointerException if s is null
Since
1.4
Definition at line 1093 of file Base64.java.
References tools.Base64.decode(), and tools.Base64.DONT_GUNZIP.
static int tools.Base64.decode4to3 (byte[] source, int srcOffset, byte[] destination, int destOffset, int options) static private
Decodes four bytes from array source and writes the resulting bytes (up to three of them) to destination. The source and destination arrays can be manipulated anywhere along their length by specifying srcOffset and destOffset. This method does not check to make sure your arrays are large enough to accomodate srcOffset + 4 for the source array or destOffset + 3 for the destination array. This method returns the actual number of bytes that were converted from the Base64 encoding.
This is the lowest level of the decoding methods with all possible parameters.
Parameters
source the array to convert
srcOffset the index where conversion begins
destination the array to hold the conversion
destOffset the index where output will be put
options alphabet type is pulled from this (standard, url-safe, ordered)
Returns
the number of decoded bytes converted
Exceptions
NullPointerException if source or destination arrays are null
IllegalArgumentException if srcOffset or destOffset are invalid or there is not enough room in the array.
Since
1.3
Definition at line 883 of file Base64.java.
References tools.Base64.getDecodabet().
Referenced by tools.Base64.decode(), and tools.Base64.decodeFileToFile().
static void tools.Base64.decodeFileToFile (String infile, String outfile) throws java.io.IOException static
Reads infile and decodes it to outfile.
Parameters
infile Input file
outfile Output file
Exceptions
java.io.IOException if there is an error
Since
2.2
Definition at line 1462 of file Base64.java.
References tools.Base64.DECODE, tools.Base64.decode4to3(), tools.Base64.decodeFromFile(), tools.Base64.DO_BREAK_LINES, tools.Base64.ENCODE, tools.Base64.encode(), tools.Base64.encode3to4(), and tools.Base64.getDecodabet().
static byte [] tools.Base64.decodeFromFile (String filename) throws java.io.IOException static
Convenience method for reading a base64-encoded file and decoding it.
As of v 2.3, if there is a error, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned false, but in retrospect that's a pretty poor way to handle it.
Parameters
filename Filename for reading encoded data
Returns
decoded byte array
Exceptions
java.io.IOException if there is an error
Since
2.1
Definition at line 1328 of file Base64.java.
References tools.Base64.DECODE.
Referenced by tools.Base64.decodeFileToFile().
static void tools.Base64.decodeToFile (String dataToDecode, String filename) throws java.io.IOException static
Convenience method for decoding data to a file.
As of v 2.3, if there is a error, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned false, but in retrospect that's a pretty poor way to handle it.
Parameters
dataToDecode Base64-encoded data as a string
filename Filename for saving decoded data
Exceptions
java.io.IOException if there is an error
Since
2.1
Definition at line 1293 of file Base64.java.
References tools.Base64.DECODE.
static Object tools.Base64.decodeToObject (String encodedObject) throws java.io.IOException, java.lang.ClassNotFoundException static
Attempts to decode Base64 data and deserialize a Java Object within. Returns null if there was an error.
Parameters
encodedObject The Base64 data to decode
Returns
The decoded and deserialized object
Exceptions
NullPointerException if encodedObject is null
java.io.IOException if there is a general error
ClassNotFoundException if the decoded object is of a class that cannot be found by the JVM
Since
1.5
Definition at line 1167 of file Base64.java.
static Object tools.Base64.decodeToObject (String encodedObject, int options, final ClassLoader loader) throws java.io.IOException, java.lang.ClassNotFoundException static
Attempts to decode Base64 data and deserialize a Java Object within. Returns null if there was an error. If loader is not null, it will be the class loader used when deserializing.
Parameters
encodedObject The Base64 data to decode
options Various parameters related to decoding
loader Optional class loader to use in deserializing classes.
Returns
The decoded and deserialized object
Exceptions
NullPointerException if encodedObject is null
java.io.IOException if there is a general error
ClassNotFoundException if the decoded object is of a class that cannot be found by the JVM
Since
2.3.4
Definition at line 1189 of file Base64.java.
References tools.Base64.decode().
static void tools.Base64.encode (java.nio.ByteBuffer raw, java.nio.ByteBuffer encoded) static
Performs Base64 encoding on the raw ByteBuffer, writing it to the encoded ByteBuffer. This is an experimental feature. Currently it does not pass along any options (such as DO_BREAK_LINES or GZIP.
Parameters
raw input buffer
encoded output buffer
Since
2.3
Definition at line 410 of file Base64.java.
References tools.Base64.encode3to4(), and tools.Base64.NO_OPTIONS.
Referenced by tools.Base64.decodeFileToFile().
static void tools.Base64.encode (java.nio.ByteBuffer raw, java.nio.CharBuffer encoded) static
Performs Base64 encoding on the raw ByteBuffer, writing it to the encoded CharBuffer. This is an experimental feature. Currently it does not pass along any options (such as DO_BREAK_LINES or GZIP.
Parameters
raw input buffer
encoded output buffer
Since
2.3
Definition at line 434 of file Base64.java.
References tools.Base64.encode3to4(), and tools.Base64.NO_OPTIONS.
static byte [] tools.Base64.encode3to4 (byte[] b4, byte[] threeBytes, int numSigBytes, int options) static private
Encodes up to the first three bytes of array threeBytes and returns a four-byte array in Base64 notation. The actual number of significant bytes in your array is given by numSigBytes. The array threeBytes needs only be as big as numSigBytes. Code can reuse a byte array by passing a four-byte array as b4.
Parameters
b4 A reusable byte array to reduce array instantiation
threeBytes the array to convert
numSigBytes the number of significant bytes in your array
Returns
four byte array in Base64 notation.
Since
1.5.1
Definition at line 319 of file Base64.java.
Referenced by tools.Base64.decodeFileToFile(), tools.Base64.encode(), and tools.Base64.encodeBytesToBytes().
static byte [] tools.Base64.encode3to4 (byte[] source, int srcOffset, int numSigBytes, byte[] destination, int destOffset, int options) static private
Encodes up to three bytes of the array source and writes the resulting four Base64 bytes to destination. The source and destination arrays can be manipulated anywhere along their length by specifying srcOffset and destOffset. This method does not check to make sure your arrays are large enough to accomodate srcOffset + 3 for the source array or destOffset + 4 for the destination array. The actual number of significant bytes in your array is given by numSigBytes.
This is the lowest level of the encoding methods with all possible parameters.
Parameters
source the array to convert
srcOffset the index where conversion begins
numSigBytes the number of significant bytes in your array
destination the array to hold the conversion
destOffset the index where output will be put
Returns
the destination array
Since
1.3
Definition at line 348 of file Base64.java.
References tools.Base64.EQUALS_SIGN, and tools.Base64.getAlphabet().
static String tools.Base64.encodeBytes (byte[] source) static
Encodes a byte array into Base64 notation. Does not GZip-compress data.
Parameters
source The data to convert
Returns
The data in Base64-encoded form
Exceptions
NullPointerException if source array is null
Since
1.4
Definition at line 567 of file Base64.java.
Referenced by tools.Base64.encodeBytes().
static String tools.Base64.encodeBytes (byte[] source, int options) throws java.io.IOException static
Encodes a byte array into Base64 notation.
Example options:
  GZIP: gzip-compresses object before encoding it.
  DO_BREAK_LINES: break lines at 76 characters
    Note: Technically, this makes your encoding non-compliant.
Example: encodeBytes(myData, Base64.GZIP) or
Example: encodeBytes(myData, Base64.GZIP | Base64.DO_BREAK_LINES)
As of v 2.3, if there is an error with the GZIP stream, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned a null value, but in retrospect that's a pretty poor way to handle it.
Parameters
source The data to convert
options Specified options
Returns
The Base64-encoded data as a String
See also
Base64::GZIP
Base64::DO_BREAK_LINES
Exceptions
java.io.IOException if there is an error
NullPointerException if source array is null
Since
2.0
Definition at line 612 of file Base64.java.
References tools.Base64.encodeBytes().
static String tools.Base64.encodeBytes (byte[] source, int off, int len) static
Encodes a byte array into Base64 notation. Does not GZip-compress data.
As of v 2.3, if there is an error, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned a null value, but in retrospect that's a pretty poor way to handle it.
Parameters
source The data to convert
off Offset in array where conversion should begin
len Length of data to convert
Returns
The Base64-encoded data as a String
Exceptions
NullPointerException if source array is null
IllegalArgumentException if source array, offset, or length are invalid
Since
1.4
Definition at line 635 of file Base64.java.
References tools.Base64.encodeBytes().
static String tools.Base64.encodeBytes (byte[] source, int off, int len, int options) throws java.io.IOException static
Encodes a byte array into Base64 notation.
Example options:
  GZIP: gzip-compresses object before encoding it.
  DO_BREAK_LINES: break lines at 76 characters
    Note: Technically, this makes your encoding non-compliant.
Example: encodeBytes(myData, Base64.GZIP) or
Example: encodeBytes(myData, Base64.GZIP | Base64.DO_BREAK_LINES)
As of v 2.3, if there is an error with the GZIP stream, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned a null value, but in retrospect that's a pretty poor way to handle it.
Parameters
source The data to convert
off Offset in array where conversion should begin
len Length of data to convert
options Specified options
Returns
The Base64-encoded data as a String
See also
Base64::GZIP
Base64::DO_BREAK_LINES
Exceptions
java.io.IOException if there is an error
NullPointerException if source array is null
IllegalArgumentException if source array, offset, or length are invalid
Since
2.0
Definition at line 683 of file Base64.java.
References tools.Base64.encodeBytesToBytes().
static byte [] tools.Base64.encodeBytesToBytes (byte[] source) static
Similar to encodeBytes(byte[]) but returns a byte array instead of instantiating a String. This is more efficient if you're working with I/O streams and have large data sets to encode.
Parameters
source The data to convert
Returns
The Base64-encoded data as a byte[] (of ASCII characters)
Exceptions
NullPointerException if source array is null
Since
2.3.1
Definition at line 710 of file Base64.java.
References tools.Base64.NO_OPTIONS.
Referenced by tools.Base64.encodeBytes().
static byte [] tools.Base64.encodeBytesToBytes (byte[] source, int off, int len, int options) throws java.io.IOException static
Similar to encodeBytes(byte[], int, int, int) but returns a byte array instead of instantiating a String. This is more efficient if you're working with I/O streams and have large data sets to encode.
Parameters
source The data to convert
off Offset in array where conversion should begin
len Length of data to convert
options Specified options
Returns
The Base64-encoded data as a String
See also
Base64::GZIP
Base64::DO_BREAK_LINES
Exceptions
java.io.IOException if there is an error
NullPointerException if source array is null
IllegalArgumentException if source array, offset, or length are invalid
Since
2.3.1
Definition at line 739 of file Base64.java.
References tools.Base64.DO_BREAK_LINES, tools.Base64.encode3to4(), tools.Base64.MAX_LINE_LENGTH, and tools.Base64.NEW_LINE.
static void tools.Base64.encodeFileToFile (String infile, String outfile) throws java.io.IOException static
Reads infile and encodes it to outfile.
Parameters
infile Input file
outfile Output file
Exceptions
java.io.IOException if there is an error
Since
2.2
Definition at line 1434 of file Base64.java.
References tools.Base64.encodeFromFile().
static String tools.Base64.encodeFromFile (String filename) throws java.io.IOException static
Convenience method for reading a binary file and base64-encoding it.
As of v 2.3, if there is a error, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned false, but in retrospect that's a pretty poor way to handle it.
Parameters
filename Filename for reading binary data
Returns
base64-encoded string
Exceptions
java.io.IOException if there is an error
Since
2.1
Definition at line 1389 of file Base64.java.
References tools.Base64.ENCODE, and tools.Base64.PREFERRED_ENCODING.
Referenced by tools.Base64.encodeFileToFile().
static String tools.Base64.encodeObject (java.io.Serializable serializableObject) throws java.io.IOException static
Serializes an object and returns the Base64-encoded version of that serialized object.
As of v 2.3, if the object cannot be serialized or there is another error, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned a null value, but in retrospect that's a pretty poor way to handle it.
The object is not GZip-compressed before being encoded.
Parameters
serializableObject The object to encode
Returns
The Base64-encoded object
Exceptions
java.io.IOException if there is an error
NullPointerException if serializedObject is null
Since
1.4
Definition at line 469 of file Base64.java.
static String tools.Base64.encodeObject (java.io.Serializable serializableObject, int options) throws java.io.IOException static
Serializes an object and returns the Base64-encoded version of that serialized object.
As of v 2.3, if the object cannot be serialized or there is another error, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned a null value, but in retrospect that's a pretty poor way to handle it.
The object is not GZip-compressed before being encoded.
Example options:
  GZIP: gzip-compresses object before encoding it.
  DO_BREAK_LINES: break lines at 76 characters
Example: encodeObject(myObj, Base64.GZIP) or
Example: encodeObject(myObj, Base64.GZIP | Base64.DO_BREAK_LINES)
Parameters
serializableObject The object to encode
options Specified options
Returns
The Base64-encoded object
See also
Base64::GZIP
Base64::DO_BREAK_LINES
Exceptions
java.io.IOException if there is an error
Since
2.0
Definition at line 505 of file Base64.java.
References tools.Base64.PREFERRED_ENCODING.
static void tools.Base64.encodeToFile (byte[] dataToEncode, String filename) throws java.io.IOException static
Convenience method for encoding data to a file.
As of v 2.3, if there is a error, the method will throw an java.io.IOException. This is new to v2.3! In earlier versions, it just returned false, but in retrospect that's a pretty poor way to handle it.
Parameters
dataToEncode byte array of data to encode in base64 form
filename Filename for saving encoded data
Exceptions
java.io.IOException if there is an error
NullPointerException if dataToEncode is null
Since
2.1
Definition at line 1257 of file Base64.java.
References tools.Base64.ENCODE.
static final byte [] tools.Base64.getAlphabet (int options) static private
Returns one of the _SOMETHING_ALPHABET byte arrays depending on the options specified. It's possible, though silly, to specify ORDERED and URLSAFE in which case one of them will be picked, though there is no guarantee as to which one will be picked.
Definition at line 265 of file Base64.java.
References tools.Base64._ORDERED_ALPHABET, tools.Base64._STANDARD_ALPHABET, and tools.Base64._URL_SAFE_ALPHABET.
Referenced by tools.Base64.encode3to4().
static final byte [] tools.Base64.getDecodabet (int options) static private
Returns one of the _SOMETHING_DECODABET byte arrays depending on the options specified. It's possible, though silly, to specify ORDERED and URL_SAFE in which case one of them will be picked, though there is no guarantee as to which one will be picked.
Definition at line 283 of file Base64.java.
References tools.Base64._ORDERED_DECODABET, tools.Base64._STANDARD_DECODABET, and tools.Base64._URL_SAFE_DECODABET.
Referenced by tools.Base64.decode(), tools.Base64.decode4to3(), and tools.Base64.decodeFileToFile().
Member Data Documentation
final byte [] tools.Base64._ORDERED_ALPHABET static private
Initial value:
= {
      (byte)'-',
      (byte)'0', (byte)'1', (byte)'2', (byte)'3', (byte)'4',
      (byte)'5', (byte)'6', (byte)'7', (byte)'8', (byte)'9',
      (byte)'A', (byte)'B', (byte)'C', (byte)'D', (byte)'E', (byte)'F', (byte)'G',
      (byte)'H', (byte)'I', (byte)'J', (byte)'K', (byte)'L', (byte)'M', (byte)'N',
      (byte)'O', (byte)'P', (byte)'Q', (byte)'R', (byte)'S', (byte)'T', (byte)'U',
      (byte)'V', (byte)'W', (byte)'X', (byte)'Y', (byte)'Z',
      (byte)'_',
      (byte)'a', (byte)'b', (byte)'c', (byte)'d', (byte)'e', (byte)'f', (byte)'g',
      (byte)'h', (byte)'i', (byte)'j', (byte)'k', (byte)'l', (byte)'m', (byte)'n',
      (byte)'o', (byte)'p', (byte)'q', (byte)'r', (byte)'s', (byte)'t', (byte)'u',
      (byte)'v', (byte)'w', (byte)'x', (byte)'y', (byte)'z'
    }
I don't get the point of this technique, but someone requested it, and it is described here: http://www.faqs.org/qa/rfcc-1940.html.
Definition at line 198 of file Base64.java.
Referenced by tools.Base64.getAlphabet().
final byte [] tools.Base64._ORDERED_DECODABET static private
Used in decoding the "ordered" dialect of Base64.
Definition at line 216 of file Base64.java.
Referenced by tools.Base64.getDecodabet().
final byte [] tools.Base64._STANDARD_ALPHABET static private
Initial value:
= {
        (byte)'A', (byte)'B', (byte)'C', (byte)'D', (byte)'E', (byte)'F', (byte)'G',
        (byte)'H', (byte)'I', (byte)'J', (byte)'K', (byte)'L', (byte)'M', (byte)'N',
        (byte)'O', (byte)'P', (byte)'Q', (byte)'R', (byte)'S', (byte)'T', (byte)'U',
        (byte)'V', (byte)'W', (byte)'X', (byte)'Y', (byte)'Z',
        (byte)'a', (byte)'b', (byte)'c', (byte)'d', (byte)'e', (byte)'f', (byte)'g',
        (byte)'h', (byte)'i', (byte)'j', (byte)'k', (byte)'l', (byte)'m', (byte)'n',
        (byte)'o', (byte)'p', (byte)'q', (byte)'r', (byte)'s', (byte)'t', (byte)'u',
        (byte)'v', (byte)'w', (byte)'x', (byte)'y', (byte)'z',
        (byte)'0', (byte)'1', (byte)'2', (byte)'3', (byte)'4', (byte)'5',
        (byte)'6', (byte)'7', (byte)'8', (byte)'9', (byte)'+', (byte)'/'
    }
The 64 valid Base64 values.
Definition at line 75 of file Base64.java.
Referenced by tools.Base64.getAlphabet().
final byte [] tools.Base64._STANDARD_DECODABET static private
Translates a Base64 value to either its 6-bit reconstruction value or a negative number indicating some other meaning.
Definition at line 93 of file Base64.java.
Referenced by tools.Base64.getDecodabet().
final byte [] tools.Base64._URL_SAFE_ALPHABET static private
Initial value:
= {
      (byte)'A', (byte)'B', (byte)'C', (byte)'D', (byte)'E', (byte)'F', (byte)'G',
      (byte)'H', (byte)'I', (byte)'J', (byte)'K', (byte)'L', (byte)'M', (byte)'N',
      (byte)'O', (byte)'P', (byte)'Q', (byte)'R', (byte)'S', (byte)'T', (byte)'U',
      (byte)'V', (byte)'W', (byte)'X', (byte)'Y', (byte)'Z',
      (byte)'a', (byte)'b', (byte)'c', (byte)'d', (byte)'e', (byte)'f', (byte)'g',
      (byte)'h', (byte)'i', (byte)'j', (byte)'k', (byte)'l', (byte)'m', (byte)'n',
      (byte)'o', (byte)'p', (byte)'q', (byte)'r', (byte)'s', (byte)'t', (byte)'u',
      (byte)'v', (byte)'w', (byte)'x', (byte)'y', (byte)'z',
      (byte)'0', (byte)'1', (byte)'2', (byte)'3', (byte)'4', (byte)'5',
      (byte)'6', (byte)'7', (byte)'8', (byte)'9', (byte)'-', (byte)'_'
    }
Used in the URL- and Filename-safe dialect described in Section 4 of RFC3548: http://www.faqs.org/rfcs/rfc3548.html. Notice that the last two bytes become "hyphen" and "underscore" instead of "plus" and "slash."
Definition at line 135 of file Base64.java.
Referenced by tools.Base64.getAlphabet().
final byte [] tools.Base64._URL_SAFE_DECODABET static private
Used in decoding URL- and Filename-safe dialects of Base64.
Definition at line 151 of file Base64.java.
Referenced by tools.Base64.getDecodabet().
final int tools.Base64.DECODE = 0 static
Specify decoding in first bit. Value is zero.
Definition at line 17 of file Base64.java.
Referenced by tools.Base64.decodeFileToFile(), tools.Base64.decodeFromFile(), and tools.Base64.decodeToFile().
final int tools.Base64.DO_BREAK_LINES = 8 static
Do break lines when encoding. Value is 8.
Definition at line 28 of file Base64.java.
Referenced by tools.Base64.decodeFileToFile(), and tools.Base64.encodeBytesToBytes().
final int tools.Base64.DONT_GUNZIP = 4 static
Specify that gzipped data should not be automatically gunzipped.
Definition at line 24 of file Base64.java.
Referenced by tools.Base64.decode().
final int tools.Base64.ENCODE = 1 static
Specify encoding in first bit. Value is one.
Definition at line 13 of file Base64.java.
Referenced by tools.Base64.decodeFileToFile(), tools.Base64.encodeFromFile(), and tools.Base64.encodeToFile().
final byte tools.Base64.EQUALS_SIGN = (byte)'=' static private
The equals sign (=) as a byte.
Definition at line 56 of file Base64.java.
Referenced by tools.Base64.encode3to4().
final byte tools.Base64.EQUALS_SIGN_ENC = -1 static private
Definition at line 68 of file Base64.java.
final int tools.Base64.GZIP = 2 static
Specify that data should be gzip-compressed in second bit. Value is two.
Definition at line 21 of file Base64.java.
final int tools.Base64.MAX_LINE_LENGTH = 76 static private
Maximum line length (76) of Base64 output.
Definition at line 52 of file Base64.java.
Referenced by tools.Base64.encodeBytesToBytes().
final byte tools.Base64.NEW_LINE = (byte)'\n' static private
The new line character (
) as a byte.
Definition at line 60 of file Base64.java.
Referenced by tools.Base64.encodeBytesToBytes().
final int tools.Base64.NO_OPTIONS = 0 static
No options specified. Value is zero.
Definition at line 10 of file Base64.java.
Referenced by tools.Base64.decode(), tools.Base64.encode(), and tools.Base64.encodeBytesToBytes().
final int tools.Base64.ORDERED = 32 static
Encode using the special "ordered" dialect of Base64 described here: http://www.faqs.org/qa/rfcc-1940.html.
Definition at line 45 of file Base64.java.
final String tools.Base64.PREFERRED_ENCODING = "US-ASCII" static private
Preferred encoding.
Definition at line 64 of file Base64.java.
Referenced by tools.Base64.encodeFromFile(), and tools.Base64.encodeObject().
final int tools.Base64.URL_SAFE = 16 static
Encode using Base64-like encoding that is URL- and Filename-safe as described in Section 4 of RFC3548: http://www.faqs.org/rfcs/rfc3548.html. It is important to note that data encoded this way is not officially valid Base64, or at the very least should not be called Base64 without also specifying that is was encoded using the URL- and Filename-safe dialect.
Definition at line 38 of file Base64.java.
final byte tools.Base64.WHITE_SPACE_ENC = -5 static private
Definition at line 67 of file Base64.java.
The documentation for this class was generated from the following file:
src/tools/Base64.java