DriverGenerator: crawler.page.PageTreeNode Class Reference
crawler.page.PageTreeNode Class Reference
Public Member Functions
PageTreeNode (String nodeName)
PageTreeNode (Document doc)
boolean equals (PageTreeNode to)
String toString ()
Public Member Functions inherited from crawler.page.GenericTreeNode< String >
GenericTreeNode ()
GenericTreeNode (T data)
GenericTreeNode< T > getParent ()
List< GenericTreeNode< T > > getChildren ()
int getNumberOfChildren ()
boolean hasChildren ()
void setChildren (List< GenericTreeNode< T >> children)
void addChild (GenericTreeNode< T > child)
void addChildAt (int index, GenericTreeNode< T > child) throws IndexOutOfBoundsException
void removeChildren ()
void removeChildAt (int index) throws IndexOutOfBoundsException
GenericTreeNode< T > getChildAt (int index) throws IndexOutOfBoundsException
T getData ()
void setData (T data)
String toString ()
String toString (int i)
boolean equals (GenericTreeNode< T > node)
int hashCode ()
String toStringFull ()
Static Public Attributes
static Set< String > excludedNode
Private Member Functions
void extractPageTree (List< Node > childNodes, PageTreeNode pt)
Additional Inherited Members
Public Attributes inherited from crawler.page.GenericTreeNode< String >
T data
List< GenericTreeNode< T > > children
GenericTreeNode< T > parent
Detailed Description
Definition at line 11 of file PageTreeNode.java.
Constructor & Destructor Documentation
crawler.page.PageTreeNode.PageTreeNode (String nodeName)
Definition at line 18 of file PageTreeNode.java.
Referenced by crawler.page.PageTreeNode.extractPageTree().
crawler.page.PageTreeNode.PageTreeNode (Document doc)
Definition at line 22 of file PageTreeNode.java.
References crawler.page.PageTreeNode.extractPageTree().
Member Function Documentation
boolean crawler.page.PageTreeNode.equals (PageTreeNode to)
Definition at line 39 of file PageTreeNode.java.
References crawler.page.GenericTreeNode< String >.data, crawler.page.GenericTreeNode< T >.data, crawler.page.GenericTreeNode< String >.getChildAt(), crawler.page.GenericTreeNode< T >.getChildAt(), crawler.page.GenericTreeNode< T >.getNumberOfChildren(), and crawler.page.GenericTreeNode< String >.getNumberOfChildren().
Referenced by crawler.WebOutput.isEquivalentTo().
void crawler.page.PageTreeNode.extractPageTree (List< Node > childNodes, PageTreeNode pt) private
Definition at line 27 of file PageTreeNode.java.
References crawler.page.GenericTreeNode< T >.addChild(), and crawler.page.PageTreeNode.PageTreeNode().
Referenced by crawler.page.PageTreeNode.PageTreeNode().
String crawler.page.PageTreeNode.toString ()
Definition at line 52 of file PageTreeNode.java.
Member Data Documentation
Set<String> crawler.page.PageTreeNode.excludedNode static
Initial value:
= new HashSet<String>(Arrays.asList(new String[] {
            "#document", "#text", "span", "font", "a", "center", "bold", "italic", "style", "base", "param", "script", "noscript",
            "b", "i", "tt", "sub", "meta", "title", "head", "tbody", "sup", "big", "small", "img", "br", "tr", "td", "option", "#comment", "#data", "strong"
            }))
Definition at line 13 of file PageTreeNode.java.
The documentation for this class was generated from the following file:
src/crawler/page/PageTreeNode.java