DriverGenerator: crawler.WebOutput Class Reference
crawler.WebOutput Class Reference
Public Member Functions
String getSource ()
Elements getDoc ()
PageTreeNode getPageTree ()
WebOutput ()
void addFrom (WebInput i)
boolean isNewFrom (WebInput i)
int getState ()
void setState (int state)
WebOutput (Document doc, WebInput from, String limitSelector)
WebOutput (String source, boolean raw, String limitSelector)
List< String > getParams ()
boolean isEquivalentTo (WebOutput to)
Private Attributes
Elements doc
String source = null
List< String > params = null
PageTreeNode pt = null
List< WebInput > from = null
int state
Detailed Description
Definition at line 12 of file WebOutput.java.
Constructor & Destructor Documentation
crawler.WebOutput.WebOutput ()
Definition at line 32 of file WebOutput.java.
crawler.WebOutput.WebOutput (Document doc, WebInput from, String limitSelector)
Definition at line 55 of file WebOutput.java.
References crawler.DriverGenerator.config, and crawler.Configuration.getLimitSelector().
crawler.WebOutput.WebOutput (String source, boolean raw, String limitSelector)
Definition at line 67 of file WebOutput.java.
Member Function Documentation
void crawler.WebOutput.addFrom (WebInput i)
Definition at line 37 of file WebOutput.java.
Elements crawler.WebOutput.getDoc ()
Definition at line 24 of file WebOutput.java.
References crawler.WebOutput.doc.
Referenced by crawler.DriverGenerator.findDifferences().
PageTreeNode crawler.WebOutput.getPageTree ()
Definition at line 28 of file WebOutput.java.
References crawler.WebOutput.pt.
List<String> crawler.WebOutput.getParams ()
Definition at line 81 of file WebOutput.java.
References crawler.WebOutput.params.
Referenced by crawler.DriverGenerator.findParameters().
String crawler.WebOutput.getSource ()
Definition at line 20 of file WebOutput.java.
References crawler.WebOutput.source.
int crawler.WebOutput.getState ()
Definition at line 47 of file WebOutput.java.
References crawler.WebOutput.state.
boolean crawler.WebOutput.isEquivalentTo (WebOutput to)
Definition at line 85 of file WebOutput.java.
References crawler.page.PageTreeNode.equals(), and crawler.WebOutput.pt.
Referenced by crawler.DriverGenerator.findParameters(), and crawler.DriverGenerator.updateOutput().
boolean crawler.WebOutput.isNewFrom (WebInput i)
Definition at line 41 of file WebOutput.java.
void crawler.WebOutput.setState (int state)
Definition at line 51 of file WebOutput.java.
References crawler.WebOutput.state.
Member Data Documentation
Elements crawler.WebOutput.doc private
Definition at line 13 of file WebOutput.java.
Referenced by crawler.WebOutput.getDoc().
List<WebInput> crawler.WebOutput.from = null private
Definition at line 17 of file WebOutput.java.
List<String> crawler.WebOutput.params = null private
Definition at line 15 of file WebOutput.java.
Referenced by crawler.WebOutput.getParams().
PageTreeNode crawler.WebOutput.pt = null private
Definition at line 16 of file WebOutput.java.
Referenced by crawler.WebOutput.getPageTree(), and crawler.WebOutput.isEquivalentTo().
String crawler.WebOutput.source = null private
Definition at line 14 of file WebOutput.java.
Referenced by crawler.WebOutput.getSource().
int crawler.WebOutput.state private
Definition at line 18 of file WebOutput.java.
Referenced by crawler.WebOutput.getState(), and crawler.WebOutput.setState().
The documentation for this class was generated from the following file:
src/crawler/WebOutput.java