DriverGenerator: crawler.WebInput Class Reference
crawler.WebInput Class Reference
Classes
enum Type
Public Member Functions
WebInput ()
void setNbValues (int val)
int getNbValues ()
void setType (Type type)
void setMethod (HttpMethod method)
void setParams (TreeMap< String, List< String >> params)
WebInput (String link)
WebInput (HttpMethod m, String address, TreeMap< String, List< String >> params)
TreeMap< String, List< String > > getParams ()
HttpMethod getMethod ()
Type getType ()
String getAddress ()
void setAddress (String address)
String toString ()
boolean equals (WebInput to)
void cleanRuntimeParameters (List< String > rtParams)
boolean isAlmostEquals (WebInput to)
Static Public Member Functions
static List< WebInput > extractInputsFromForm (Element form)
Private Attributes
int nbValues = 0
Type type = null
HttpMethod method = null
String address = null
TreeMap< String, List< String > > params = null
Detailed Description
Definition at line 13 of file WebInput.java.
Constructor & Destructor Documentation
crawler.WebInput.WebInput ()
Definition at line 24 of file WebInput.java.
Referenced by crawler.WebInput.extractInputsFromForm().
crawler.WebInput.WebInput (String link)
Definition at line 48 of file WebInput.java.
References crawler.WebInput.Type.LINK.
crawler.WebInput.WebInput (HttpMethod m, String address, TreeMap< String, List< String >> params)
Definition at line 70 of file WebInput.java.
References crawler.WebInput.address, crawler.WebInput.Type.FORM, and crawler.WebInput.params.
Member Function Documentation
void crawler.WebInput.cleanRuntimeParameters (List< String > rtParams)
Definition at line 187 of file WebInput.java.
References crawler.WebInput.Type.FORM, and crawler.WebInput.Type.LINK.
boolean crawler.WebInput.equals (WebInput to)
Definition at line 171 of file WebInput.java.
References crawler.WebInput.address, and crawler.WebInput.params.
static List<WebInput> crawler.WebInput.extractInputsFromForm (Element form) static
Definition at line 77 of file WebInput.java.
References tools.Utils.createArrayList(), and crawler.WebInput.WebInput().
Referenced by crawler.DriverGenerator.crawl().
String crawler.WebInput.getAddress ()
Definition at line 159 of file WebInput.java.
References crawler.WebInput.address.
Referenced by crawler.DriverGenerator.addInput(), crawler.DriverGenerator.crawlInput(), and crawler.DriverGenerator.prettyprint().
HttpMethod crawler.WebInput.getMethod ()
Definition at line 151 of file WebInput.java.
References crawler.WebInput.method.
int crawler.WebInput.getNbValues ()
Definition at line 32 of file WebInput.java.
References crawler.WebInput.nbValues.
TreeMap<String, List<String> > crawler.WebInput.getParams ()
Definition at line 147 of file WebInput.java.
References crawler.WebInput.params.
Referenced by crawler.DriverGenerator.addInput(), crawler.DriverGenerator.addProvidedParameter(), crawler.DriverGenerator.crawlInput(), crawler.DriverGenerator.getRandomValuesForInput(), crawler.DriverGenerator.getValuesForInput(), crawler.DriverGenerator.mergeInputs(), and crawler.DriverGenerator.prettyprint().
Type crawler.WebInput.getType ()
Definition at line 155 of file WebInput.java.
References crawler.WebInput.type.
Referenced by crawler.DriverGenerator.crawlInput(), crawler.DriverGenerator.getRandomValuesForInput(), and crawler.DriverGenerator.getValuesForInput().
boolean crawler.WebInput.isAlmostEquals (WebInput to)
Definition at line 222 of file WebInput.java.
References crawler.WebInput.address, and crawler.WebInput.params.
void crawler.WebInput.setAddress (String address)
Definition at line 163 of file WebInput.java.
References crawler.WebInput.address.
void crawler.WebInput.setMethod (HttpMethod method)
Definition at line 40 of file WebInput.java.
References crawler.WebInput.method.
void crawler.WebInput.setNbValues (int val)
Definition at line 28 of file WebInput.java.
void crawler.WebInput.setParams (TreeMap< String, List< String >> params)
Definition at line 44 of file WebInput.java.
References crawler.WebInput.params.
void crawler.WebInput.setType (Type type)
Definition at line 36 of file WebInput.java.
References crawler.WebInput.type.
String crawler.WebInput.toString ()
Definition at line 167 of file WebInput.java.
Member Data Documentation
String crawler.WebInput.address = null private
Definition at line 21 of file WebInput.java.
Referenced by crawler.WebInput.equals(), crawler.WebInput.getAddress(), crawler.WebInput.isAlmostEquals(), crawler.WebInput.setAddress(), and crawler.WebInput.WebInput().
HttpMethod crawler.WebInput.method = null private
Definition at line 20 of file WebInput.java.
Referenced by crawler.WebInput.getMethod(), and crawler.WebInput.setMethod().
int crawler.WebInput.nbValues = 0 private
Definition at line 18 of file WebInput.java.
Referenced by crawler.WebInput.getNbValues().
TreeMap<String, List<String> > crawler.WebInput.params = null private
Definition at line 22 of file WebInput.java.
Referenced by crawler.WebInput.equals(), crawler.WebInput.getParams(), crawler.WebInput.isAlmostEquals(), crawler.WebInput.setParams(), and crawler.WebInput.WebInput().
Type crawler.WebInput.type = null private
Definition at line 19 of file WebInput.java.
Referenced by crawler.WebInput.getType(), and crawler.WebInput.setType().
The documentation for this class was generated from the following file:
src/crawler/WebInput.java