DriverGenerator: crawler.Configuration Class Reference
crawler.Configuration Class Reference
Public Member Functions
boolean keepSmallSet ()
void setsmallestSet (boolean b)
List< String > getURLs ()
Configuration ()
void setHost (String host)
String getReset ()
void setReset (String reset)
void setPort (int port)
void setBasicAuthUser (String basicAuthUser)
void setBasicAuthPass (String basicAuthPass)
void setName (String name)
void setMergeInputs (boolean m)
void setLimitSelector (String limitSelector)
void setNoFollow (ArrayList< String > noFollow)
void setActionByParameter (String actionByParameter)
String getActionByParameter ()
List< String > getNoFollow ()
String getName ()
String getCookies ()
String getBasicAuthUser ()
String getBasicAuthPass ()
String getHost ()
int getPort ()
String getLimitSelector ()
Map< String, ArrayList< String > > getData ()
boolean getMerge ()
void check ()
void setCookies (String cookies)
Private Attributes
String host = null
int port = 0
String basicAuthUser = null
String basicAuthPass = null
String name = null
String limitSelector = null
HashMap< String, ArrayList< String > > paramValues = null
ArrayList< String > noFollow = null
ArrayList< String > urls = null
String actionByParameter = null
String cookies = null
String reset = null
boolean mergeInputs = false
boolean smallestSet = false
Detailed Description
Definition at line 13 of file Configuration.java.
Constructor & Destructor Documentation
crawler.Configuration.Configuration ()
Definition at line 41 of file Configuration.java.
Member Function Documentation
void crawler.Configuration.check ()
Definition at line 142 of file Configuration.java.
References tools.loggers.LogManager.logException(), and tools.loggers.LogManager.logFatalError().
Referenced by crawler.DriverGenerator.DriverGenerator().
String crawler.Configuration.getActionByParameter ()
Definition at line 91 of file Configuration.java.
References crawler.Configuration.actionByParameter.
Referenced by crawler.DriverGenerator.addInput(), and crawler.DriverGenerator.prettyprint().
String crawler.Configuration.getBasicAuthPass ()
Definition at line 116 of file Configuration.java.
References crawler.Configuration.basicAuthPass.
Referenced by crawler.DriverGenerator.DriverGenerator(), and crawler.DriverGenerator.exportToXML().
String crawler.Configuration.getBasicAuthUser ()
Definition at line 112 of file Configuration.java.
References crawler.Configuration.basicAuthUser.
Referenced by crawler.DriverGenerator.DriverGenerator(), and crawler.DriverGenerator.exportToXML().
String crawler.Configuration.getCookies ()
Definition at line 103 of file Configuration.java.
Referenced by crawler.DriverGenerator.DriverGenerator(), and crawler.DriverGenerator.exportToXML().
Map<String, ArrayList<String> > crawler.Configuration.getData ()
Definition at line 133 of file Configuration.java.
References crawler.Configuration.paramValues.
Referenced by crawler.DriverGenerator.addProvidedParameter(), and crawler.DriverGenerator.DriverGenerator().
String crawler.Configuration.getHost ()
Definition at line 120 of file Configuration.java.
References crawler.Configuration.host.
Referenced by crawler.DriverGenerator.DriverGenerator(), and crawler.DriverGenerator.exportToXML().
String crawler.Configuration.getLimitSelector ()
Definition at line 128 of file Configuration.java.
References crawler.Configuration.limitSelector.
Referenced by crawler.DriverGenerator.crawl(), crawler.DriverGenerator.exportToXML(), crawler.DriverGenerator.findParameters(), crawler.DriverGenerator.updateOutput(), and crawler.WebOutput.WebOutput().
boolean crawler.Configuration.getMerge ()
Definition at line 138 of file Configuration.java.
References crawler.Configuration.mergeInputs.
Referenced by crawler.DriverGenerator.start().
String crawler.Configuration.getName ()
Definition at line 99 of file Configuration.java.
References crawler.Configuration.name.
Referenced by crawler.DriverGenerator.exportToDot(), crawler.DriverGenerator.exportToXML(), and crawler.DriverGenerator.getName().
List<String> crawler.Configuration.getNoFollow ()
Definition at line 95 of file Configuration.java.
References crawler.Configuration.noFollow.
Referenced by crawler.DriverGenerator.filterUrl().
int crawler.Configuration.getPort ()
Definition at line 124 of file Configuration.java.
References crawler.Configuration.port.
Referenced by crawler.DriverGenerator.DriverGenerator(), and crawler.DriverGenerator.exportToXML().
String crawler.Configuration.getReset ()
Definition at line 51 of file Configuration.java.
References crawler.Configuration.reset.
Referenced by crawler.DriverGenerator.reset().
List<String> crawler.Configuration.getURLs ()
Definition at line 37 of file Configuration.java.
References crawler.Configuration.urls.
Referenced by crawler.DriverGenerator.DriverGenerator().
boolean crawler.Configuration.keepSmallSet ()
Definition at line 29 of file Configuration.java.
References crawler.Configuration.smallestSet.
Referenced by crawler.DriverGenerator.addInput().
void crawler.Configuration.setActionByParameter (String actionByParameter)
Definition at line 87 of file Configuration.java.
References crawler.Configuration.actionByParameter.
void crawler.Configuration.setBasicAuthPass (String basicAuthPass)
Definition at line 67 of file Configuration.java.
References crawler.Configuration.basicAuthPass.
void crawler.Configuration.setBasicAuthUser (String basicAuthUser)
Definition at line 63 of file Configuration.java.
References crawler.Configuration.basicAuthUser.
void crawler.Configuration.setCookies (String cookies)
Definition at line 164 of file Configuration.java.
References crawler.Configuration.cookies.
void crawler.Configuration.setHost (String host)
Definition at line 47 of file Configuration.java.
References crawler.Configuration.host.
void crawler.Configuration.setLimitSelector (String limitSelector)
Definition at line 79 of file Configuration.java.
References crawler.Configuration.limitSelector.
void crawler.Configuration.setMergeInputs (boolean m)
Definition at line 75 of file Configuration.java.
void crawler.Configuration.setName (String name)
Definition at line 71 of file Configuration.java.
References crawler.Configuration.name.
void crawler.Configuration.setNoFollow (ArrayList< String > noFollow)
Definition at line 83 of file Configuration.java.
References crawler.Configuration.noFollow.
void crawler.Configuration.setPort (int port)
Definition at line 59 of file Configuration.java.
References crawler.Configuration.port.
void crawler.Configuration.setReset (String reset)
Definition at line 55 of file Configuration.java.
References crawler.Configuration.reset.
void crawler.Configuration.setsmallestSet (boolean b)
Definition at line 33 of file Configuration.java.
Member Data Documentation
String crawler.Configuration.actionByParameter = null private
Definition at line 23 of file Configuration.java.
Referenced by crawler.Configuration.getActionByParameter(), and crawler.Configuration.setActionByParameter().
String crawler.Configuration.basicAuthPass = null private
Definition at line 17 of file Configuration.java.
Referenced by crawler.Configuration.getBasicAuthPass(), and crawler.Configuration.setBasicAuthPass().
String crawler.Configuration.basicAuthUser = null private
Definition at line 16 of file Configuration.java.
Referenced by crawler.Configuration.getBasicAuthUser(), and crawler.Configuration.setBasicAuthUser().
String crawler.Configuration.cookies = null private
Definition at line 24 of file Configuration.java.
Referenced by crawler.Configuration.setCookies().
String crawler.Configuration.host = null private
Definition at line 14 of file Configuration.java.
Referenced by crawler.Configuration.getHost(), and crawler.Configuration.setHost().
String crawler.Configuration.limitSelector = null private
Definition at line 19 of file Configuration.java.
Referenced by crawler.Configuration.getLimitSelector(), and crawler.Configuration.setLimitSelector().
boolean crawler.Configuration.mergeInputs = false private
Definition at line 26 of file Configuration.java.
Referenced by crawler.Configuration.getMerge().
String crawler.Configuration.name = null private
Definition at line 18 of file Configuration.java.
Referenced by crawler.Configuration.getName(), and crawler.Configuration.setName().
ArrayList<String> crawler.Configuration.noFollow = null private
Definition at line 21 of file Configuration.java.
Referenced by crawler.Configuration.getNoFollow(), and crawler.Configuration.setNoFollow().
HashMap<String, ArrayList<String> > crawler.Configuration.paramValues = null private
Definition at line 20 of file Configuration.java.
Referenced by crawler.Configuration.getData().
int crawler.Configuration.port = 0 private
Definition at line 15 of file Configuration.java.
Referenced by crawler.Configuration.getPort(), and crawler.Configuration.setPort().
String crawler.Configuration.reset = null private
Definition at line 25 of file Configuration.java.
Referenced by crawler.Configuration.getReset(), and crawler.Configuration.setReset().
boolean crawler.Configuration.smallestSet = false private
Definition at line 27 of file Configuration.java.
Referenced by crawler.Configuration.keepSmallSet().
ArrayList<String> crawler.Configuration.urls = null private
Definition at line 22 of file Configuration.java.
Referenced by crawler.Configuration.getURLs().
The documentation for this class was generated from the following file:
src/crawler/Configuration.java