DriverGenerator: tools.HTTPData Class Reference
tools.HTTPData Class Reference
Public Member Functions
HTTPData ()
HTTPData (String name, String value)
HTTPData (HashMap< String, String > paramValues)
void add (String name, String value)
HashMap< String, String > getData ()
List< NameValuePair > getNameValueData ()
String toString ()
Private Attributes
HashMap< String, String > data = null
Detailed Description
Definition at line 9 of file HTTPData.java.
Constructor & Destructor Documentation
tools.HTTPData.HTTPData ()
Definition at line 12 of file HTTPData.java.
tools.HTTPData.HTTPData (String name, String value)
Definition at line 16 of file HTTPData.java.
tools.HTTPData.HTTPData (HashMap< String, String > paramValues)
Definition at line 21 of file HTTPData.java.
Member Function Documentation
void tools.HTTPData.add (String name, String value)
Definition at line 26 of file HTTPData.java.
Referenced by crawler.DriverGenerator.getRandomValuesForInput(), and crawler.DriverGenerator.getValuesForInput().
HashMap<String, String> tools.HTTPData.getData ()
Definition at line 30 of file HTTPData.java.
References tools.HTTPData.data.
List<NameValuePair> tools.HTTPData.getNameValueData ()
Definition at line 34 of file HTTPData.java.
Referenced by crawler.DriverGenerator.submit(), and crawler.DriverGenerator.submitRandom().
String tools.HTTPData.toString ()
Definition at line 42 of file HTTPData.java.
Member Data Documentation
HashMap<String, String> tools.HTTPData.data = null private
Definition at line 10 of file HTTPData.java.
Referenced by tools.HTTPData.getData().
The documentation for this class was generated from the following file:
src/tools/HTTPData.java