SIMPA: crawler.DriverGeneratorBFS Class Reference
crawler.DriverGeneratorBFS Class Reference
Inherits crawler.DriverGenerator.
Protected Member Functions
WebOutput sendInputChain (WebInput input, boolean withoutLast) throws IOException
String sendInput (WebInput input, boolean randomized) throws IOException
int crawlInput (WebInput start)
void updateOutput (Document d, WebInput from)
void updateOutput (WebOutput out, WebInput from)
Map< String, String > findDifferences (WebOutput first, WebOutput second)
Detailed Description
This class implements a web site crawling using a Breadth-first search
Definition at line 41 of file DriverGeneratorBFS.java.
Member Function Documentation
int crawler.DriverGeneratorBFS.crawlInput (WebInput start) protected
The inputs corresponding to the current depth
The inputs of the next depth
Definition at line 173 of file DriverGeneratorBFS.java.
References crawler.DriverGeneratorBFS.sendInputChain(), and crawler.DriverGeneratorBFS.updateOutput().
Map<String, String> crawler.DriverGeneratorBFS.findDifferences (WebOutput first, WebOutput second) protected
Find the different values between two equivalent pages
Parameters
first the first page
second the second page
Returns
a structure mapping the paths (in the DOM) of the differences, and a sample value (arbitrarily taken from 'first')
Definition at line 330 of file DriverGeneratorBFS.java.
Referenced by crawler.DriverGeneratorBFS.updateOutput().
String crawler.DriverGeneratorBFS.sendInput (WebInput input, boolean randomized) throws IOException protected
Actually send an input to the web application
Parameters
input the WebInput to send
randomized if true, sends random (or ramdomly picked) values for each parameter
Returns
the content of the output (most likely HTML)
Exceptions
MalformedURLException
Definition at line 129 of file DriverGeneratorBFS.java.
WebOutput crawler.DriverGeneratorBFS.sendInputChain (WebInput input, boolean withoutLast) throws IOException protected
Sends a sequence of inputs to the web application.
Parameters
input the WebInput containing the sequence to send
withoutLast if true, the last input of the sequence (i.e 'input') will not be sent
Returns
the last obtained output
Exceptions
MalformedURLException
Definition at line 65 of file DriverGeneratorBFS.java.
Referenced by crawler.DriverGeneratorBFS.crawlInput(), and crawler.DriverGeneratorBFS.updateOutput().
void crawler.DriverGeneratorBFS.updateOutput (Document d, WebInput from) protected
Parameters
d The output document to check
See also
updateOutput(WebOutput out, WebInput from)
Definition at line 263 of file DriverGeneratorBFS.java.
Referenced by crawler.DriverGeneratorBFS.crawlInput().
void crawler.DriverGeneratorBFS.updateOutput (WebOutput out, WebInput from) protected
Checks if the output page has already been seen, and if so, checks if it is the first time we access it with the given input.
Parameters
out The output to check
from The input used to access the page
Definition at line 275 of file DriverGeneratorBFS.java.
References crawler.DriverGeneratorBFS.findDifferences(), and crawler.DriverGeneratorBFS.sendInputChain().
The documentation for this class was generated from the following file:
src/crawler/DriverGeneratorBFS.java