J48: Entropy Class Reference
Entropy Class Reference
Static Public Member Functions
static float _Entropy (LinkedList< String > column, Nominal< String > enum_values)
static float gain (LinkedList< String > column_class, LinkedList< String > column, Nominal enum_class, Nominal enum_col, float global_entropy)
static float gainO (LinkedList< String > column_class, LinkedList< String > column, Nominal enum_class, Nominal enum_col, float global_entropy)
Detailed Description
Definition at line 8 of file Entropy.java.
Member Function Documentation
static float Entropy._Entropy (LinkedList< String > column, Nominal< String > enum_values) static
Definition at line 9 of file Entropy.java.
References Nominal< T >.getLinkedList().
Referenced by gain(), gainO(), J48.main(), and ID3.Run().
static float Entropy.gain (LinkedList< String > column_class, LinkedList< String > column, Nominal enum_class, Nominal enum_col, float global_entropy) static
Definition at line 43 of file Entropy.java.
References _Entropy(), and Nominal< T >.getLinkedList().
Referenced by gainO(), J48.main(), and ID3.SelectBestColumn().
static float Entropy.gainO (LinkedList< String > column_class, LinkedList< String > column, Nominal enum_class, Nominal enum_col, float global_entropy) static
Definition at line 68 of file Entropy.java.
References _Entropy(), gain(), Nominal< T >.getLinkedList(), and Nominal< T >.size().
The documentation for this class was generated from the following file:
src/Entropy.java