J48: ArffReader Class Reference
ArffReader Class Reference
Public Member Functions
ArffReader (String r_file) throws java.io.IOException
String getRelation ()
Map< String, Type > getTypeAttributes ()
Map< Integer, String > getArrayAttributes ()
ArrayList< LinkedList > getColumnsAttributes ()
Map< String, Nominal< String > > getMapAttributes ()
Map< String[], String > getHashTrain ()
Private Member Functions
String ArffReadRelation () throws java.io.IOException
void GenerateMapAttributes ()
void ArffReadHeader () throws java.io.IOException
void ArffReadData () throws java.io.IOException
Private Attributes
Scanner m_reader
File arff_file
Map< String, Type > type_attributes
Map< Integer, String > array_attributes
Map< String[], String > hash_train
ArrayList< LinkedList > columns_attributes
Map< String, Nominal< String > > map_attributes
String relation
Detailed Description
Definition at line 11 of file ArffReader.java.
Constructor & Destructor Documentation
ArffReader.ArffReader (String r_file) throws java.io.IOException
Definition at line 23 of file ArffReader.java.
References ArffReadData(), ArffReadHeader(), ArffReadRelation(), and GenerateMapAttributes().
Member Function Documentation
void ArffReader.ArffReadData () throws java.io.IOException private
Definition at line 149 of file ArffReader.java.
Referenced by ArffReader().
void ArffReader.ArffReadHeader () throws java.io.IOException private
Definition at line 91 of file ArffReader.java.
References Nominal< T >.add().
Referenced by ArffReader().
String ArffReader.ArffReadRelation () throws java.io.IOException private
Definition at line 60 of file ArffReader.java.
References relation.
Referenced by ArffReader().
void ArffReader.GenerateMapAttributes () private
Definition at line 76 of file ArffReader.java.
References Nominal< T >.add(), and Nominal< T >.exist().
Referenced by ArffReader().
Map<Integer, String> ArffReader.getArrayAttributes ()
Definition at line 44 of file ArffReader.java.
References array_attributes.
Referenced by J48.main().
ArrayList<LinkedList> ArffReader.getColumnsAttributes ()
Definition at line 48 of file ArffReader.java.
References columns_attributes.
Referenced by J48.main().
Map<String[], String> ArffReader.getHashTrain ()
Definition at line 56 of file ArffReader.java.
References hash_train.
Map<String, Nominal<String> > ArffReader.getMapAttributes ()
Definition at line 52 of file ArffReader.java.
References map_attributes.
Referenced by J48.main().
String ArffReader.getRelation ()
Definition at line 36 of file ArffReader.java.
References relation.
Referenced by J48.main().
Map<String, Type> ArffReader.getTypeAttributes ()
Definition at line 40 of file ArffReader.java.
References type_attributes.
Referenced by J48.main().
Member Data Documentation
File ArffReader.arff_file private
Definition at line 14 of file ArffReader.java.
Map<Integer, String> ArffReader.array_attributes private
Definition at line 16 of file ArffReader.java.
Referenced by getArrayAttributes().
ArrayList<LinkedList> ArffReader.columns_attributes private
Definition at line 18 of file ArffReader.java.
Referenced by getColumnsAttributes().
Map<String[], String> ArffReader.hash_train private
Definition at line 17 of file ArffReader.java.
Referenced by getHashTrain().
Scanner ArffReader.m_reader private
Definition at line 13 of file ArffReader.java.
Map<String, Nominal<String> > ArffReader.map_attributes private
Definition at line 19 of file ArffReader.java.
Referenced by getMapAttributes().
String ArffReader.relation private
Definition at line 20 of file ArffReader.java.
Referenced by ArffReadRelation(), and getRelation().
Map<String, Type> ArffReader.type_attributes private
Definition at line 15 of file ArffReader.java.
Referenced by getTypeAttributes().
The documentation for this class was generated from the following file:
src/ArffReader.java