J48: ID3 Class Reference
ID3 Class Reference
Static Public Member Functions
static DecisionTree Run (ArrayList< LinkedList > columns_attributes, LinkedList< String > col_class, Map< String, Nominal< String >> map_attributes, Map< Integer, String > array_attributes, int index_class)
Static Private Member Functions
static String MostPresent (LinkedList< String > column, LinkedList< String > possible_values)
static int SelectBestColumn (LinkedList< String > column_class, ArrayList< LinkedList > columns_attributes, Map< String, Nominal< String >> map_attributes, Map< Integer, String > array_attributes, int index_class, float Global_Entropy)
static int GetIndexColAtt (int index, int index_class)
static ArrayList< LinkedList > DeleteColumn (ArrayList< LinkedList > columns_attributes, int index)
static ArrayList< LinkedList > FilterColAtt (ArrayList< LinkedList > columns_attributes, String value, int index)
static Map< Integer, String > FilterArrAtt (Map< Integer, String > array_attributes, int best_column)
Private Attributes
int indexBestAttribut
Detailed Description
Definition at line 8 of file ID3.java.
Member Function Documentation
static ArrayList<LinkedList> ID3.DeleteColumn (ArrayList< LinkedList > columns_attributes, int index) static private
Definition at line 146 of file ID3.java.
Referenced by FilterColAtt().
static Map<Integer, String> ID3.FilterArrAtt (Map< Integer, String > array_attributes, int best_column) static private
Definition at line 184 of file ID3.java.
Referenced by Run().
static ArrayList<LinkedList> ID3.FilterColAtt (ArrayList< LinkedList > columns_attributes, String value, int index) static private
Definition at line 157 of file ID3.java.
References DeleteColumn().
Referenced by Run().
static int ID3.GetIndexColAtt (int index, int index_class) static private
Definition at line 140 of file ID3.java.
static String ID3.MostPresent (LinkedList< String > column, LinkedList< String > possible_values) static private
Definition at line 90 of file ID3.java.
Referenced by Run().
static DecisionTree ID3.Run (ArrayList< LinkedList > columns_attributes, LinkedList< String > col_class, Map< String, Nominal< String >> map_attributes, Map< Integer, String > array_attributes, int index_class) static
Definition at line 12 of file ID3.java.
References Entropy._Entropy(), DecisionTree.AddChildrenNode(), FilterArrAtt(), FilterColAtt(), Nominal< T >.getLinkedList(), MostPresent(), Run(), SelectBestColumn(), and DecisionTree.setTag().
Referenced by J48.main(), and Run().
static int ID3.SelectBestColumn (LinkedList< String > column_class, ArrayList< LinkedList > columns_attributes, Map< String, Nominal< String >> map_attributes, Map< Integer, String > array_attributes, int index_class, float Global_Entropy) static private
Definition at line 123 of file ID3.java.
References Entropy.gain().
Referenced by Run().
Member Data Documentation
int ID3.indexBestAttribut private
Definition at line 10 of file ID3.java.
The documentation for this class was generated from the following file:
src/ID3.java