J48: DecisionTree Class Reference
DecisionTree Class Reference
Public Member Functions
DecisionTree ()
DecisionTree (Tag t)
Tag getTag ()
void setTag (Tag t)
void calculHeight ()
void setHeight (int h)
int getHeight ()
LinkedList< DecisionTree > getChildren ()
boolean isLeaf ()
void removeChildren ()
Condition getCondition ()
Static Public Member Functions
static String toString (DecisionTree n)
static void AddChildrenNode (DecisionTree node, DecisionTree child)
static void AddChildren (DecisionTree node, Tag t)
static DecisionTree getChild (DecisionTree DT, String value)
static DecisionTree Optimize (DecisionTree DT)
static ClassificationResult Predict (DecisionTree DT)
Private Member Functions
void DecorTree ()
Static Private Member Functions
static String Reduction (DecisionTree DT)
Private Attributes
Tag tag
DecisionTree parent
LinkedList< DecisionTree > children
Condition condition
Detailed Description
Definition at line 7 of file DecisionTree.java.
Constructor & Destructor Documentation
DecisionTree.DecisionTree ()
Definition at line 14 of file DecisionTree.java.
Referenced by AddChildren(), and Optimize().
DecisionTree.DecisionTree (Tag t)
Definition at line 22 of file DecisionTree.java.
Member Function Documentation
static void DecisionTree.AddChildren (DecisionTree node, Tag t) static
Definition at line 98 of file DecisionTree.java.
References AddChildrenNode(), children, and DecisionTree().
static void DecisionTree.AddChildrenNode (DecisionTree node, DecisionTree child) static
Definition at line 69 of file DecisionTree.java.
References children, and parent.
Referenced by AddChildren(), Optimize(), and ID3.Run().
void DecisionTree.calculHeight ()
Definition at line 78 of file DecisionTree.java.
References calculHeight(), and setHeight().
Referenced by calculHeight(), and toString().
void DecisionTree.DecorTree () private
Definition at line 181 of file DecisionTree.java.
References getCondition().
Referenced by Predict().
static DecisionTree DecisionTree.getChild (DecisionTree DT, String value) static
Definition at line 104 of file DecisionTree.java.
References children, Tag.getValue(), and tag.
LinkedList<DecisionTree> DecisionTree.getChildren ()
Definition at line 115 of file DecisionTree.java.
References children.
Referenced by Optimize(), Predict(), and Reduction().
Condition DecisionTree.getCondition ()
Definition at line 177 of file DecisionTree.java.
References condition.
Referenced by DecorTree(), and Predict().
int DecisionTree.getHeight ()
Definition at line 94 of file DecisionTree.java.
Referenced by toString().
Tag DecisionTree.getTag ()
Definition at line 30 of file DecisionTree.java.
References tag.
Referenced by Predict(), and Reduction().
boolean DecisionTree.isLeaf ()
Definition at line 119 of file DecisionTree.java.
Referenced by Optimize(), Predict(), and Reduction().
static DecisionTree DecisionTree.Optimize (DecisionTree DT) static
Definition at line 153 of file DecisionTree.java.
References AddChildrenNode(), DecisionTree(), getChildren(), isLeaf(), Reduction(), and removeChildren().
Referenced by J48.main().
static ClassificationResult DecisionTree.Predict (DecisionTree DT) static
Definition at line 192 of file DecisionTree.java.
References DecorTree(), getChildren(), getCondition(), getTag(), Tag.getValue(), isLeaf(), and parent.
Referenced by J48.main().
static String DecisionTree.Reduction (DecisionTree DT) static private
Definition at line 129 of file DecisionTree.java.
References getChildren(), getTag(), Tag.getValue(), and isLeaf().
Referenced by Optimize().
void DecisionTree.removeChildren ()
Definition at line 125 of file DecisionTree.java.
Referenced by Optimize().
void DecisionTree.setHeight (int h)
Definition at line 90 of file DecisionTree.java.
Referenced by calculHeight().
void DecisionTree.setTag (Tag t)
Definition at line 34 of file DecisionTree.java.
Referenced by ID3.Run().
static String DecisionTree.toString (DecisionTree n) static
Definition at line 38 of file DecisionTree.java.
References calculHeight(), children, getHeight(), Tag.getValue(), tag, Tag.toString(), and toString().
Referenced by J48.main(), and toString().
Member Data Documentation
LinkedList<DecisionTree> DecisionTree.children private
Definition at line 10 of file DecisionTree.java.
Referenced by AddChildren(), AddChildrenNode(), getChild(), getChildren(), and toString().
Condition DecisionTree.condition private
Definition at line 12 of file DecisionTree.java.
Referenced by getCondition().
DecisionTree DecisionTree.parent private
Definition at line 9 of file DecisionTree.java.
Referenced by AddChildrenNode(), and Predict().
Tag DecisionTree.tag private
Definition at line 8 of file DecisionTree.java.
Referenced by getChild(), getTag(), and toString().
The documentation for this class was generated from the following file:
src/DecisionTree.java