J48: Nominal< T > Class Template Reference
Nominal< T > Class Template Reference
Public Member Functions
Nominal ()
Nominal (T val)
void add (T val)
void remove (T val)
LinkedList< T > getNominal ()
int size ()
LinkedList< T > getLinkedList ()
boolean exist (T val)
String toString ()
Detailed Description
Definition at line 4 of file Nominal.java.
Constructor & Destructor Documentation
Nominal< T >.Nominal ()
Definition at line 7 of file Nominal.java.
Nominal< T >.Nominal (T val)
Definition at line 11 of file Nominal.java.
Member Function Documentation
void Nominal< T >.add (T val)
Definition at line 16 of file Nominal.java.
Referenced by ArffReader.ArffReadHeader(), and ArffReader.GenerateMapAttributes().
boolean Nominal< T >.exist (T val)
Definition at line 36 of file Nominal.java.
Referenced by ArffReader.GenerateMapAttributes().
LinkedList<T> Nominal< T >.getLinkedList ()
Definition at line 32 of file Nominal.java.
Referenced by Entropy._Entropy(), Entropy.gain(), Entropy.gainO(), and ID3.Run().
LinkedList<T> Nominal< T >.getNominal ()
Definition at line 24 of file Nominal.java.
void Nominal< T >.remove (T val)
Definition at line 20 of file Nominal.java.
int Nominal< T >.size ()
Definition at line 28 of file Nominal.java.
Referenced by Entropy.gainO().
String Nominal< T >.toString ()
Definition at line 42 of file Nominal.java.
The documentation for this class was generated from the following file:
src/Nominal.java